# Generated by Django 2.0.8 on 2018-10-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181003_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('missions', 'Missions'), ('politics', 'Politics'), ('discoveries', 'Discoveries')], max_length=256),
        ),
    ]
